FROM ubuntu:20.04

RUN apt-get update && apt-get install -y openssh-server sudo

RUN mkdir /var/run/sshd

RUN echo 'root:root' | chpasswd

RUN useradd -ms /bin/bash user1 && echo 'user1:user1' | chpasswd && adduser user1 sudo

EXPOSE 22

CMD ["/usr/sbin/sshd","-D"]